### ISSUE TITLE
Standalone?

### ISSUE THREAD

**Issue by geeknik** [attekett/NodeFuzz#5]
Thank you for providing this excellent piece of software. What would be the best way to edit this so that it doesn't launch or close a browser and just runs as a standalone server in which we can just point various browsers on the network at? We handle our own crash collection, instrumentation, and analytics and we're just looking to run this without any of the extras, just fuzz the browser.

**Comment by attekett** [comment]
Thanks for the compliment. It has been a while since I last time modified NodeFuzz, so going with fast check on the code and what I can remember.

NodeFuzz requires an instrumentation module, but if I recall right you can just implement empty instrumentation module, that actually does nothing. Then NodeFuzz will start the server and start serving test cases to any browser connecting to it until end of time, or websocket disconnect. 

In that approach there is no way for you to collect the test cases from the NodeFuzz instance, you would need to collect them from the browser executing the test case. Do you need to get the generated test cases from NodeFuzz?

Another thing is that NodeFuzz was not designed to handle multiple browsers, so you would need to create a NodeFuzz instance  for each browser connecting, or modify the core so that there can be more than one WebSocket instance at the same time. I actually had to add quite a few variables like _sending_ and _websocketConnected_ to actually prevent misbehaving browser from connecting multiple times to NodeFuzz, so that may be tricky.

If I were to serve multiple browsers with NodeFuzz I would probably either spin up _N_ NodeFuzz instances to start with, or put another server in front. When that server would get a new connection, it would spawn a new NodeFuzz instance to a random port and redirect the browser to there. Old instances could be cleared with an instrumentation module that closes NodeFuzz when websocket connection is disconnect or with a large timeout.

I hope this helped. If you hit some specific issue or problem, I can spend some more time refreshing my memories with the code during weekend.

**Comment by geeknik** [comment]
Thank you for the prompt reply. I was hoping a request into an ancient repo would be heard. (; 

> Then NodeFuzz will start the server and start serving test cases to any browser connecting to it until end of time

Perfect. 

> Do you need to get the generated test cases from NodeFuzz?

No, I believe our client-side test harness should be able to capture that. 

> Another thing is that NodeFuzz was not designed to handle multiple browsers

No worries.

**Comment by attekett** [comment]
Closing as it seems resolved. Please open a new issue if there is still something I can help with.
